import { UserIdentityAdminClient } from '../src'
async function adminTest() {
	const userIdentityAdmin = new UserIdentityAdminClient({
		baseUrl: 'http://localhost:3000',
	})
	userIdentityAdmin.setTokenId(
		'eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ3YjE5MTI0MGZjZmYzMDdkYzQ3NTg1OWEyYmUzNzgzZGMxYWY4OWYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmFyZS1ndWlkZS0zNTIwMDIiLCJhdWQiOiJyYXJlLWd1aWRlLTM1MjAwMiIsImF1dGhfdGltZSI6MTY2NzU1MjE3MSwidXNlcl9pZCI6IktWTXVNSWFrTE5lR1JWSnU5T2RiWHROdzBXMjMiLCJzdWIiOiJLVk11TUlha0xOZUdSVkp1OU9kYlh0TncwVzIzIiwiaWF0IjoxNjY4MDYxNzgzLCJleHAiOjE2NjgwNjUzODMsImVtYWlsIjoiekBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiekBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.WtyYKr-F2R-9x_GaYTcbsluIWf-asGkdUCJbIpmnaEgEfLtf6QFK2sitGVYkj-25H1Z_xdkmU5ihVLvnZlMdvMJgz_Km7vakxLn18PQhqA_LjG8VlTkYoXGp_RdEZtD6oN3XAgf9wTo45vXCKXc0Z3pmfh4-OHlFTtUgxbttQtVELXz-vKKBsfhZ5GS3GgVpoYWs0_gbxwZrtAs5k9TXA7TCHCLa86P0iPQRNz1ClbgOAY91zGPmSPSO28DJaho4Se5JU3W1aMWRPqNOAXPkY8T6oyuYkp42lAeUiyhLSPMvvOO0n53MmwifUkTsQmOCy0oFatJE7kXAoC_37u5DhQ',
	)

	const loginResp = await userIdentityAdmin.login('avisadmin4@coinhe.io', 'okNga@11')
	console.log(loginResp)
}

adminTest().catch(console.error)
