{{- if .Values.spot.enable }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ template "main.fullname" . }}-spot
 labels:
   app: {{ template "main.name" . }}
   chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
   release: {{ .Release.Name }}
   heritage: {{ .Release.Service }}
spec:
    {{- if .Values.spot.podAutoscaler }}
{{ toYaml .Values.spot.podAutoscaler | indent 2 }}
    {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "main.fullname" . }}-spot
{{- end }}