{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "main.fullname" . }}
spec:
  gateways:
  - {{ template "main.fullname" . }}-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: {{ template "main.fullname" . }}
        port:
          number: {{ .Values.service.externalPort }}
    match:
    - uri:
        prefix: {{ .Values.istio.uriPrefix }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "main.fullname" . }}-gateway
spec:
  selector:
    istio: {{ .Values.istio.gateway }}
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: GRPC
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: {{ template "main.fullname" . }}
spec:
  mtls:
    mode: DISABLE
{{- end }}